version: "3.8"
services:
  nginx_proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - '80:80'
      - "8090:81"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.dev.conf:/data/nginx/custom/http_top.conf
    depends_on:
      - frontend
      - backend 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
   