apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-backend
  template:
    metadata:
      labels:
        app: react-backend
    spec:
      containers:
      - name: react-backend
        image: paularinze/qr-code-frontend:latest
        ports:
        -containerPort: 3000


apiVersion: v1
kind: Service
metadata:
  name: react-backend-service
spec:
  type: LoadBalancer
  selector:
    app: react-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000