apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image:paularinze/react-frontend:latest

apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: ClusterIP
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80